# Process the AGAP airborne gravity data

We try to recreate the BAS processing steps, as outlined here: https://data.bas.ac.uk/full-record.php?id=GB/NERC/BAS/PDC/01310

In [1]:
# %load_ext autoreload
# %autoreload 2

import boule as bl
import cmocean
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import verde as vd

import airbornegeo

## Load data

This is a subset of the BAS AGAP survey over Antarctica's Gamburtsev Subglacial Mountains. The file is download and subset in the notebook `AGAP_survey`.

In [2]:
data_df = pd.read_csv("data/AGAP_gravity_survey.csv")

print(data_df.columns)
data_df.head()

Index(['Lon', 'Lat', 'Height_WGS1984', 'Date', 'Time', 'ST', 'CC', 'RB',
       'XACC', 'LACC', 'Still', 'Base', 'ST_real', 'Beam_vel', 'rec_grav',
       'Abs_grav', 'VaccCor', 'EotvosCor', 'LatCor', 'FaCor', 'HaccCor',
       'Free_air', 'FAA_filt', 'FAA_clip', 'Level_cor', 'FAA_level',
       'Fa_4600m', 'easting', 'northing', 'line_name', 'line', 'unixtime'],
      dtype='str')

,Lon,Lat,Height_WGS1984,Date,Time,ST,CC,RB,XACC,LACC,...,FAA_filt,FAA_clip,Level_cor,FAA_level,Fa_4600m,easting,northing,line_name,line,unixtime
0,77.252450,-80.583923,4156.1,2008-12-17,0 days 09:42:48,11934.47,2.61,-659.0,-49.0,273.0,...,49.38,49.38,7.03,42.4,40.8,1.000024e+06,226237.330771,11_DA500,1,1.229507e+09
1,77.252672,-80.583377,4156.0,2008-12-17,0 days 09:42:49,11934.47,2.72,-368.6,-321.0,230.0,...,49.45,49.45,7.04,42.4,40.8,1.000083e+06,226246.631269,11_DA500,1,1.229507e+09
2,77.252901,-80.582831,4156.1,2008-12-17,0 days 09:42:50,11888.95,-2.08,703.1,433.0,146.0,...,49.52,49.52,7.04,42.5,40.9,1.000142e+06,226255.809132,11_DA500,1,1.229507e+09
3,77.253131,-80.582285,4156.4,2008-12-17,0 days 09:42:51,11888.95,0.50,625.1,566.0,223.0,...,49.58,49.58,7.03,42.5,40.9,1.000201e+06,226264.969079,11_DA500,1,1.229507e+09
4,77.253358,-80.581740,4156.6,2008-12-17,0 days 09:42:52,11888.95,-1.73,575.1,108.0,205.0,...,49.65,49.65,7.04,42.6,41.0,1.000260e+06,226274.156809,11_DA500,1,1.229507e+09

In [ ]:
survey = airbornegeo.Survey(
    data_df,
    line_column="line",
    time_column="unixtime",
    height_column="Height_WGS1984",
    latitude_column="Lat",
    longitude_column="Lon",
    distance_column="distance_along_line",
)
survey

## Distance along line

In [ ]:
survey.along_track_distance()
survey.data[["easting", "northing", "distance_along_line"]].head()

## Relative gravity
$$
g_{rel} = s (t +(b k)+c)
$$

where $g_{rel}$ is the relative gravity, $t$ is the true spring tension, $b$ is the beam velocity, $k$ is 30, $c$ is the cross-coupling, and $s$ is the meter scale value, which is 0.9966.

The beam velocity ($b$) is from a centered finite difference  approximation of the raw beam position ($RB$).

In [ ]:
survey.data["grav_relative"] = 0.9966 * (
    survey.data["ST_real"] + (survey.data["Beam_vel"] * 30) + survey.data["CC"]
)
survey.data[
    ["unixtime", "RB", "Beam_vel", "CC", "ST", "ST_real", "grav_relative"]
].head()

In [ ]:
max_abs = vd.maxabs(survey.data.grav_relative, percentile=95)

survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="grav_relative",
    s=0.6,
    cmap=cmocean.cm.balance,
    vmin=-max_abs,
    vmax=max_abs,
).set_aspect("equal")

In [ ]:
# for now just use there values
survey.data = data_df.drop(columns=["grav_relative"], errors="ignore")
survey.data["grav_relative"] = data_df.rec_grav

## Absolute gravity

Still readings are in mGal and were calculating assuming a 2nd order best fit to the approximately linear drift of the meter observed at the tie down points. For each line, there are 2-5 unique still values. For the whole survey, the base station readings are all equal to 981970.73 mGal.

Absolute gravity is then calculated as:
$$
g_{abs} = g_{rel} - g_{still} + g_{base}
$$

In [ ]:
survey.data["grav_absolute"] = (
    survey.data["grav_relative"] - survey.data["Still"] + survey.data["Base"]
)
survey.data[["grav_relative", "Base", "Still", "grav_absolute"]].head()

In [ ]:
cpt_lims = vd.minmax(survey.data.grav_absolute, min_percentile=5, max_percentile=95)

survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="grav_absolute",
    s=0.6,
    vmin=cpt_lims[0],
    vmax=cpt_lims[1],
).set_aspect("equal")

In [ ]:
# for now just use their values
survey.data = data_df.drop(columns=["grav_absolute"], errors="ignore")
survey.data["grav_absolute"] = data_df.Abs_grav

## Vertical acceleration corrections

The vertical acceleration is calculated as the 2nd derivative of flight altitude w.r.t. time with a 3 point mean filter applied after differencing to reduce short wavelength noise.

In [ ]:
survey.vertical_acceleration(
    smoothing_window=3,
    result_column="vertical_acceleration",
)
# Convert from m/s2 to mGal (already done by the method via result multiplier)
survey.data.describe()

In [ ]:
df = survey.data[survey.data.line == 1]

ylim = vd.minmax(df.VaccCor)  # , min_percentile=5, max_percentile=95)

ax = df.plot.line(
    "distance_along_line",
    "vertical_acceleration",
    style="bp",
    ms=1,
    ylim=ylim,
)

ax = df.plot.line(
    "distance_along_line",
    "VaccCor",
    style="rx",
    ms=1,
    # ax=ax,
    ylim=ylim,
)

In [ ]:
survey.data["dif"] = survey.data.VaccCor - survey.data.vertical_acceleration
sns.histplot(survey.data.dif, kde=True)
plt.title(
    f"Vertical acceleration difference with published values, RMSE:{round(airbornegeo.rmse(survey.data.dif), 2)}"
)
plt.show()

In [ ]:
# for now just use the BAS values
survey.data = data_df.drop(columns=["vertical_acceleration"], errors="ignore")
survey.data["vertical_acceleration"] = data_df.VaccCor

## Horizontal acceleration corrections

For this survey the approximation of Swain 1996 was used, assuming a damping of 0.707 and a platform period of 4 minutes.

In [14]:
# data_df['horizontal_acceleration'] = (
#     data_df.XACC**2 +
#     data_df.LACC**2 -
#     (np.diff(airbornegeo.eastward_velocity(
#         data_df.Lat.values, data_df.Lon.values, data_df.unixtime.values
#     ), prepend=np.nan) / data_df.unixtime.diff() )**2 -
#     (np.diff(airbornegeo.northward_velocity(
#         data_df.Lat.values, data_df.Lon.values, data_df.unixtime.values
#     ), prepend=np.nan) / data_df.unixtime.diff() )**2
# ) / 2*data_df.grav_relative

In [ ]:
# for now just use the BAS values
survey.data = survey.data.drop(columns=["horizontal_acceleration"], errors="ignore")
survey.data["horizontal_acceleration"] = survey.data.HaccCor

## Eotvos correction

In [ ]:
survey.ground_speed()

cpt_lims = vd.minmax(survey.data.ground_speed, min_percentile=5, max_percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="ground_speed",
    s=0.6,
    vmin=cpt_lims[0],
    vmax=cpt_lims[1],
).set_aspect("equal")

In [ ]:
survey.track(ellipsoid=False)  # this is faster

cpt_lims = vd.minmax(survey.data.track, min_percentile=5, max_percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="track",
    s=0.6,
    vmin=cpt_lims[0],
    vmax=cpt_lims[1],
).set_aspect("equal")

In [ ]:
survey.eotvos_correction(method="glicken")
cpt_lims = vd.minmax(survey.data.eotvos_correction, min_percentile=5, max_percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="eotvos_correction",
    s=0.6,
    vmin=cpt_lims[0],
    vmax=cpt_lims[1],
).set_aspect("equal")

In [ ]:
survey.eotvos_correction(method="glicken")
cpt_lims = vd.minmax(survey.data.eotvos_correction, min_percentile=5, max_percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="eotvos_correction",
    s=0.6,
    vmin=cpt_lims[0],
    vmax=cpt_lims[1],
).set_aspect("equal")

In [ ]:
df = survey.data[survey.data.line == 1]

ylim = vd.minmax(df.EotvosCor)  # , min_percentile=5, max_percentile=95)

ax = df.plot.line(
    "distance_along_line",
    "eotvos_correction",
    style="bp",
    ms=1,
    ylim=ylim,
)

ax = df.plot.line(
    "distance_along_line",
    "EotvosCor",
    style="rx",
    ms=1,
    ax=ax,
    ylim=ylim,
)

In [ ]:
survey.data["dif"] = survey.data.EotvosCor - survey.data.eotvos_correction
sns.histplot(survey.data.dif, kde=True)
plt.title(
    f"Eötvös correction difference with published values, RMSE:{round(airbornegeo.rmse(survey.data.dif), 2)}"
)
plt.show()

In [ ]:
# for now just use the BAS values
survey.data = data_df.drop(columns=["eotvos_correction"], errors="ignore")
survey.data["eotvos_correction"] = data_df.EotvosCor

## Observed gravity

In [ ]:
survey.data["grav_observed"] = (
    survey.data["grav_absolute"]
    - survey.data["vertical_acceleration"]
    + survey.data["eotvos_correction"]
    - (0.5 * survey.data["horizontal_acceleration"])
)

In [ ]:
cpt_lims = vd.minmax(survey.data.grav_observed, min_percentile=5, max_percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="grav_observed",
    s=0.6,
    vmin=cpt_lims[0],
    vmax=cpt_lims[1],
).set_aspect("equal")

In [ ]:
df = survey.data[survey.data.line == 1]

ylim = vd.minmax(df.grav_observed)  # , min_percentile=5, max_percentile=95)

ax = df.plot.line(
    "distance_along_line",
    "grav_observed",
    style="bp",
    ms=1,
    ylim=ylim,
)

## Normal gravity corrections 

BAS used a separate latitude correction and free-air correction. We will instead combine them with a Normal gravity correction.

In [ ]:
# combine the published Latitude and Free air corrections into a Normal gravity column
survey.data["NormalGrav"] = survey.data.LatCor - survey.data.FaCor

In [ ]:
# Calculate normal gravity using the WGS84 ellipsoid
ellipsoid = bl.WGS84

survey.data["grav_normal"] = ellipsoid.normal_gravity(
    (None, survey.data.Lat, survey.data.Height_WGS1984)
)

In [ ]:
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="grav_normal",
    s=0.6,
).set_aspect("equal")

In [ ]:
df = survey.data[survey.data.line == 1]
ax = df.plot.line(
    "distance_along_line",
    "grav_normal",
    style="bp",
    ms=1,
)
ax = df.plot.line(
    "distance_along_line",
    "NormalGrav",
    style="rx",
    ms=1,
    ax=ax,
)

In [ ]:
survey.data["dif"] = survey.data.NormalGrav - survey.data.grav_normal
sns.histplot(survey.data.dif, kde=True)
plt.title(
    f"Normal gravity difference with published values, RMSE:{round(airbornegeo.rmse(survey.data.dif), 2)}"
)
plt.show()

In [ ]:
# for now just use the BAS values
survey.data = data_df.drop(columns=["grav_normal"], errors="ignore")
survey.data["grav_normal"] = data_df.NormalGrav

## Gravity Distrubance

In [ ]:
# The disturbance is the observed minus normal gravity (calculated at the
# observation point)
survey.data["grav_disturbance"] = data_df.grav_observed - data_df.grav_normal

In [ ]:
cpt_lims = vd.maxabs(survey.data.Free_air, percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="grav_disturbance",
    s=0.6,
    cmap=cmocean.cm.balance,
    vmin=-cpt_lims,
    vmax=cpt_lims,
).set_aspect("equal")

In [ ]:
survey.data["dif"] = survey.data.Free_air - survey.data.grav_disturbance
sns.histplot(survey.data.dif, kde=True)
plt.title(
    f"Gravity disturbance (FAA) difference with published values, RMSE:{round(airbornegeo.rmse(survey.data.dif), 2)}"
)
plt.show()

In [ ]:
df = survey.data[survey.data.line == 1]

ylim = vd.minmax(df.grav_disturbance)  # , min_percentile=5, max_percentile=95)

ax = df.plot.line(
    "distance_along_line",
    "grav_disturbance",
    style="bp",
    ms=1,
    ylim=ylim,
)

ax = df.plot.line(
    "distance_along_line",
    "Free_air",
    style="rx",
    ms=1,
    ax=ax,
    ylim=ylim,
)

In [ ]:
# for now just use the BAS values
survey.data = data_df.drop(columns=["grav_disturbance"], errors="ignore")
survey.data["grav_disturbance"] = data_df.Free_air

## Filtering

Filtered free air anomaly (FAA_filt) used 9 km 1/2 wavelength space domain kernel filter (Holt et al., 2006).

In [ ]:
survey.filter_line(
    filter_width=26_000,
    filter_type="lowpass",
    data_column="grav_disturbance",
    result_column="grav_disturbance_filt",
    pad_width_percentage=20,
)

In [ ]:
cpt_lims = vd.maxabs(survey.data.FAA_filt, percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="grav_disturbance_filt",
    s=0.6,
    cmap=cmocean.cm.balance,
    vmin=-cpt_lims,
    vmax=cpt_lims,
).set_aspect("equal")

In [ ]:
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="FAA_filt",
    s=0.6,
    cmap=cmocean.cm.balance,
    vmin=-cpt_lims,
    vmax=cpt_lims,
).set_aspect("equal")

In [ ]:
survey.data["dif"] = survey.data.FAA_filt - survey.data.grav_disturbance_filt
sns.histplot(survey.data.dif, kde=True)
plt.title(
    f"filtered FAA difference with published values, RMSE:{round(airbornegeo.rmse(survey.data.dif), 2)}"
)
plt.show()

In [ ]:
cpt_lims = vd.maxabs(survey.data.dif, percentile=95)
survey.data[::50].plot.scatter(
    "easting",
    "northing",
    c="dif",
    s=0.6,
    cmap=cmocean.cm.balance,
    vmin=-cpt_lims,
    vmax=cpt_lims,
).set_aspect("equal")

In [ ]:
df = survey.data[survey.data.line == 1]

ylim = vd.minmax(df.FAA_filt)  # , min_percentile=5, max_percentile=95)

ax = df.plot.line(
    "distance_along_line",
    "grav_disturbance_filt",
    style="bp",
    ms=1,
    ylim=ylim,
)

ax = df.plot.line(
    "distance_along_line",
    "FAA_filt",
    style="rx",
    ms=1,
    ax=ax,
    ylim=ylim,
)

In [ ]:
# for now just use the BAS values
survey.data = data_df.drop(columns=["grav_disturbance_filt"], errors="ignore")
survey.data["grav_disturbance_filt"] = data_df.FAA_filt

## Save the results

In [ ]:
survey.data.columns

In [ ]:
# save to csv for further levelling notebook
# eventually will use our version, but for checking the levelling is working correctly,
# we will just use their version
df = survey.data

df = df.rename(
    columns={
        "Level_cor": "level_correction",
        "FAA_level": "grav_disturbance_filt_level",
        "Height_WGS1984": "height",
        "Lon": "longitude",
        "Lat": "latitude",
    }
)

df = df[
    [
        "line",
        "easting",
        "northing",
        "longitude",
        "latitude",
        "height",
        "unixtime",
        "distance_along_line",
        "grav_observed",
        "grav_disturbance",
        "grav_disturbance_filt",
        "level_correction",
        "grav_disturbance_filt_level",
    ]
]

df = df.reset_index(drop=True)
df

In [46]:
df.to_csv("data/AGAP_gravity_survey_processed.csv", index=False)

In [47]:
# block reduce by line to speed up the notebooks
df_blocked = airbornegeo.block_reduce(
    df,
    np.median,
    spacing=200,
    reduce_by="distance_along_line",
    groupby_column="line",
)
df_blocked

Block-reducing segments:   0%|          | 0/100 [00:00<?, ?it/s]

,distance_along_line,tmp,line,easting,northing,longitude,latitude,height,unixtime,grav_observed,grav_disturbance,grav_disturbance_filt,level_correction,grav_disturbance_filt_level
0,89.767924,0.0,1,1.000112e+06,226251.220201,77.252786,-80.583104,4156.10,1.229507e+09,982375.8575,581.05,49.485,7.035,42.45
1,299.027209,0.0,1,1.000319e+06,226283.309168,77.253587,-80.581195,4156.90,1.229507e+09,981105.9000,-716.70,49.710,7.030,42.70
2,507.126130,0.0,1,1.000525e+06,226314.585668,77.254418,-80.579297,4159.60,1.229507e+09,981213.4300,-584.35,49.920,7.035,42.90
3,713.391042,0.0,1,1.000729e+06,226345.184353,77.255265,-80.577416,4163.30,1.229507e+09,980694.7050,-1092.30,50.110,7.030,43.10
4,888.955840,0.0,1,1.000903e+06,226371.179740,77.255988,-80.575815,4165.00,1.229507e+09,982786.7400,1011.00,50.270,7.030,43.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107007,78243.550033,0.0,100,1.587849e+06,497160.759515,72.614485,-74.773032,2116.45,1.230382e+09,982357.5600,182.25,-17.505,NaN,NaN
107008,78427.756923,0.0,100,1.587882e+06,496979.685445,72.620783,-74.773230,2116.70,1.230382e+09,982478.8800,292.30,-17.370,NaN,NaN
107009,78612.860388,0.0,100,1.587914e+06,496797.241880,72.627100,-74.773453,2115.55,1.230382e+09,981880.3200,-337.90,-17.205,NaN,NaN
107010,78826.103942,0.0,100,1.587950e+06,496587.151406,72.634381,-74.773705,2113.20,1.230382e+09,982215.1500,-12.55,-16.990,NaN,NaN
107011,79041.150831,0.0,100,1.587987e+06,496375.310967,72.641724,-74.773957,2110.90,1.230382e+09,983405.7125,1175.90,-16.725,NaN,NaN

In [ ]:
# block reduce by line to speed up the notebooks
df_blocked = airbornegeo.block_reduce(
    survey.data,
    np.median,
    spacing=200,
    reduce_by="distance_along_line",
    groupby_column="line",
)
df_blocked